import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link';

const Home = () => {
    return (
        <div className={ styles.container }>
            <Head>
                <title>Gimme Spells. Gimme All the Spells.</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className={ styles.main }>
                <h1 className={ styles.title }>
                    We've got spells and more,<br/>
                    but just ask us about the spells for now
                </h1>

                <p className={ styles.description }>
                    Keeping this here for later
                </p>

                <div className={ styles.grid }>
                    <Link href={ '/spells/arcanist' } className={ styles.card }>
                        <h2>Arcanist Spells &rarr;</h2>
                        <p>Check out some fancy arcanist spells.</p>
                    </Link>

                    <Link href={ '/spells/diviner' } className={ styles.card }>
                        <h2>Diviner Spells &rarr;</h2>
                        <p>If you don't like the arcanist spells, become a diviner</p>
                    </Link>
                </div>
            </main>

        </div>
    )
}

export default Home;